prepare for x-cmd-version

diff --git a/.x-cmd/fabu-release b/.x-cmd/fabu-release
--- a/.x-cmd/fabu-release
+++ b/.x-cmd/fabu-release
@@ -1,11 +1,26 @@
 # shellcheck shell=dash
 
+(
 git clone git@github.com:x-cmd/release
-cd release
-if xws build; then
-    git add .
-    git commit -m ...
-    git push git@github.com:x-cmd/release main
-    git push git@gitee.com:x-cmd/release main
-    git push git@gitcode.net:x-cmd/release main
-fi
+
+distfolder="$PWD/release/dist"
+sumfolder="$PWD/release/sum"
+mkdir -p "$distfolder" "$sumfolder"
+
+(
+git clone git@github.com:x-cmd/x-cmd-version
+cd x-cmd-version
+
+xws release "$distfolder" "$sumfolder" || exit 1
+) || exit
+
+(
+cd release || x:error "Cannot cd to release"
+git add .
+git commit -m ...
+git push git@github.com:x-cmd/release main
+git push git@gitee.com:x-cmd/release main
+git push git@gitcode.net:x-cmd/release main
+)
+
+)
